#!/bin/sh

if [ -z "$DBUS_SESSION_BUS_ADDRESS" ] ; then
	eval $(dbus-launch --sh-syntax --exit-with-session)
fi

# X apps
xset -dpms s 0 0 &
xsetroot -cursor_name left_ptr &
xrdb -load ~/.config/x11/xresources &
xbindkeys -f /home/kino/.config/x11/xbindkeysrc &
xwallpaper --zoom /home/kino/Pictures/Wallpapers/lodoss_deedlit.jpg &
# music player daemon
mpd &
# compositor
picom &
# clipboard maanger
clipmenu daemon &
# light temp
redshift  -c ~/.config/redshift/config &
# window manager
exec bspwm
