#!/bin/bash

picom --vsync &
pulseaudio --start &
xbindkeys -f /home/kino/.config/X11/xbindkeysrc &
launch-polybar &
tilix &
xwallpaper --zoom /home/kino/Pictures/Wallpapers/astronaut.jpg &
exec bspwm
