#!/bin/bash

if [ -z "$DBUS_SESSION_BUS_ADDRESS" ] ; then
	eval $(dbus-launch --sh-syntax --exit-with-session)
fi

# compositor
picom &
~/.config/rofi/clipmenu daemon &
xbacklight -set 50 &
xsetroot -cursor_name left_ptr &
redshift  -c ~/.config/redshift/config &
xbindkeys -f /home/kino/.config/X11/xbindkeysrc &
xwallpaper --zoom /home/kino/Pictures/Wallpapers/astronaut.jpg &
polybar -q main -c /home/kino/.config/polybar/config.ini &
exec bspwm
