#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &
pgrep -x yabar > /dev/null || yabar &

bspc monitor -d 1 2 3 4 5

bspc config border_width         2
bspc config window_gap           5

bspc config split_ratio          0.5
bspc config borderless_monocle   true
bspc config gapless_monocle      true
