#!/bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &
pgrep -x polybar > /dev/null || polybar &

bspc monitor -d 1 2 3

bspc config border_width         2
bspc config window_gap           0

bspc config split_ratio          0.5
bspc config borderless_monocle   false
bspc config gapless_monocle      false

bspc config focused_border_color "#88c0d0"
#bspc config normal_border_color  "#b75154"
bspc config normal_border_color  "#343940"
