#!/bin/sh

FILE="$1"
CACHE=$(mktemp /tmp/thumbcache.XXXXX)

#########################
## Handle by extension ##
#########################
case ${FILE##*.} in
	a|ace|alz|apk|arc|arj|bz|bz2|cab|cpio|deb|gz|iso|jar|lha|lz|lzh|lzma|lzo|rpm|rz|t7z|tar|tbz|tbz2|tgz|tlz|txz|tZ|tzo|war|xpi|xz|Z|zip|zst)
		tar -tvf "$FILE" && exit 1;;
	rar|cbr)
		unrar l "$FILE" && exit 1;;
	7z)
		7z l -p -- "$FILE" && exit 1;;
	*) ;; 
esac
##########################
## Handle by mime types ##
##########################
case "$(file -Lb --mime-type -- "$FILE")" in
	text/*|*/xml|*/csv|*/json)
		bat --style=plain --paging=never --color=always "$FILE" && exit 1;;
	image/svg*)
		magick convert "$FILE" -resize 100% "$CACHE.png"
		~/.config/lf/image draw "$CACHE.png" "$2" "$3" "$4" "$5" "$6" && exit 1;;
	image/*)
		timg --grid=3x2 "$FILE" && exit 1;;
		# chafa -C yes -s "${2}x${3}" "$FILE" && exit 1;;
		#kitty +kitten icat --clear --stdin no --silent --transfer-mode file < /dev/null > /dev/tty
		#kitty +kitten icat --silent --stdin no --transfer-mode file --place "${2}x${3}@${4}x${5}" "$FILE" < /dev/null > /dev/tty && exit 1;;
	video/*)
		ffmpeg -y -ss 00:00:10.000 -i "$FILE" -vframes 1 "$CACHE.png"
		~/.config/lf/image draw "$CACHE.png" "$2" "$3" "$4" "$5" "$6" && exit 1;;
	audio/*)
		exiftool "$FILE" && exit 1;;
	application/octet-stream)
		file -b -- "$FILE" && exit 1;;
	application/vnd.oasis*)
		odt2txt "$FILE" && exit 1;;
	application/pdf)
		pdftoppm -png -f 1 -singlefile "$FILE" "$CACHE"
		~/.config/lf/image draw "$CACHE.png" "$2" "$3" "$4" "$5" "$6" && exit 1;;

	*) ;; 
esac
################################################
## None of above exits, this is the fall back ##
################################################
echo '----- File Type Classification -----'
file -b -- "$FILE" && exit 1;;

