# .bashrc

# If not running interactively, don't do anything
[[ $- != *i* ]] && return


# Set up starship
eval "$(starship init bash)"

# Alias
alias cl='clear'
alias xxx='exit'
alias ...='cd ..'
# Flatpak
alias fii='flatpak install'
alias fcc='flatpak uninstall --unused'
alias fuu='flatpak update'
alias frr='flatpak uninstall'
alias fll='flatpak list'
# Python
alias cvenv='python -m venv env'
alias avenv='source env/bin/activate'
alias dvenv='deactivate'
# NPM
alias vtop='npx vtop'
alias nodemon='npx nodemon'
alias serve='npx serve -s'
# XBPS
alias iii='sudo vpm install' # xbps-install -S
alias uuu='sudo vpm update' # xbps-install -Su
alias rrr='sudo vpm removerecursive' # xbps-remove -Rf
alias ccc='sudo vpm cleanup ; sudo vpm autoremove' # xbps-remove -Oofv
alias sss='sudo vpm search'
alias fff='sudo vpm info'
# Others
alias lll='lsd -la'
alias cl='clear'
alias xxx='exit'
alias ...='cd ..'
alias ssh-gen="ssh-keygen -t rsa -b 4069 -C"
alias reboot='sudo reboot'
alias poweroff='sudo poweroff'

pfetch


# PS1='[\u@\h \W]\$ '
