#!/bin/bash

# If not running interactively, don't do anything
[[ $- != *i* ]] && return


# Set up starship
eval "$(starship init bash)"

###########
## Alias ##
###########

# Flatpak
alias fii='flatpak install'
alias fcc='flatpak uninstall --unused'
alias fuu='flatpak update'
alias frr='flatpak uninstall'
alias fll='flatpak list'
alias fee='flatpak run'
alias fss='flatpak search'
alias librewolf='flatpak run io.gitlab.librewolf-community &'
alias peazip='flatpak run io.github.peazip.Peazip &'
alias flatseal='flatpak run com.github.tchx84.Flatseal &'
alias mgba='flatpak run io.mgba.mGBA &'
alias smplayer='flatpak run info.smplayer.SMPlayer'
# Git
alias gst='git status'
alias gaa='git add .'
alias gcm='git commit -m'
alias gps='git push'
alias gpl='git pull'
# Python
alias cvenv='python -m venv env'
alias avenv='source env/bin/activate'
alias dvenv='deactivate'
# NPM
alias nodemon='npx nodemon'
alias serve='npx serve -s'
# XBPS
alias iii='sudo vpm install'
alias uuu='sudo vpm update'
alias rrr='sudo vpm removerecursive'
alias ccc='sudo vpm cleanup ; sudo vpm autoremove'
alias sss='sudo vpm search'
alias fff='sudo vpm info'
# Power commands
alias reboot='loginctl reboot'
alias poweroff='loginctl poweroff'
alias logout='((sleep 1; loginctl kill-user kino) & bspc quit)'
# Commands
alias sudoers='sudo nvim /etc/sudoers.d/wheel'
alias edit-grub='sudo nvim /etc/default/grub'
alias up-grub='sudo update-grub'
alias polybar='pkill polybar; sleep 1; polybar -q main -c /home/kino/.config/polybar/config.ini &'
alias xdgninja='~/.bin/xdg-ninja/xdg-ninja.sh'
alias lf='~/.config/lf/lf || ~/.config/lf/lf'
alias ssh-gen='ssh-keygen -t rsa -b 4069 -C'
alias ftp5871='lftp kino@192.168.58.71:2121'
alias bat='bat --style=plain --paging=never --color=always'
alias clpfe='clear;pfetch'
alias monerod='monerod --data-dir "$XDG_DATA_HOME"/bitmonero'
# Apps
alias screenshot='xfce4-screenshooter &'
alias codium='(sleep 5 ; rm -rf ~/.pki/ ~/.vscode-oss/) & ~/.bin/vscodium/bin/codium --user-data-dir ~/.config/VSCodium/ --extensions-dir ~/.config/VSCodium/extensions/'
alias bulkr='thunar -B'
# Basics
alias la='lsd -la'
alias ls='lsd -l'
alias cl='clear'
alias rm='rm -rf'
alias xx='exit'
alias ..='cd ..'

rm ~/Desktop
rm ~/.thumbnails

