# .bashrc

# If not running interactively, don't do anything
[[ $- != *i* ]] && return


# Set up starship
eval "$(starship init bash)"

# Alias
# Flatpak
alias fii='flatpak install'
alias fcc='flatpak uninstall --unused'
alias fuu='flatpak update'
alias frr='flatpak uninstall'
alias fll='flatpak list'
# Python
alias cvenv='python -m venv env'
alias avenv='source env/bin/activate'
alias dvenv='deactivate'
# NPM
alias vtop='npx vtop'
alias nodemon='npx nodemon'
alias serve='npx serve -s'
# XBPS
alias iii='sudo vpm install'
alias uuu='sudo vpm update'
alias rrr='sudo vpm removerecursive'
alias ccc='sudo vpm cleanup ; sudo vpm autoremove'
alias sss='sudo vpm search'
alias fff='sudo vpm info'
# Others
alias ll='lsd -l'
alias la='lsd -la'
alias cl='clear'
alias xxx='exit'
alias ...='cd ..'
alias ssh-gen="ssh-keygen -t rsa -b 4069 -C"
alias reboot='sudo reboot'
alias poweroff='sudo poweroff'

